### ISSUE TITLE
crash during load.

### ISSUE THREAD

**Issue by mmmthepotatogod** [Nova-Committee/ThrowableSlimeball#1]
im using the 1.16.5 version of the mod (1.0.1), latest mod and latest forge.
the issue is with the language provider (needs javafml:38 or above)
i can provide a crash report and/or latest log if needed
overall, seems like a great mod!

**Comment by VulpesStella** [comment]
Got it, try manually changing that "[38,)" to "[36,)" in your mods.toml before my fix on it

**Comment by mmmthepotatogod** [comment]
> Got it, try manually changing that "[38,)" to "[36,)" in your mods.toml before my fix on it

wdym? im not sure if you mean the file name, mods folder, config, or smt completly different.
not too good with mods and java errors... :(

**Comment by VulpesStella** [comment]
[zipped_mod_file.zip](https://github.com/Nova-Committee/ThrowableSlimeball/files/13113643/zipped_mod_file.zip)

**Comment by mmmthepotatogod** [comment]
> [zipped_mod_file.zip](https://github.com/Nova-Committee/ThrowableSlimeball/files/13113643/zipped_mod_file.zip)

amazing!
thanks so much mate!
also, thanks for the quick fixes and answers, your'e a life saver (a bit less. but you get the point)! :D

**Comment by VulpesStella** [comment]
Ur welcome lol
I didn't test the mod in 1.16.5 production env(was busy porting it to every major version).
Any problem, plz reopen the issue :DD

**Comment by mmmthepotatogod** [comment]
welp uhhh.....
sorry to be a trouble maker, but  i found 2 new problems :|
1. both projectiles are invis. they still work and hurt, but invis.
2. both slime balls and magma creams are no longer appear on jei. (and maybe the creative menu too).
also, just to let you know, im using a lot of different mods, so the issues might only be on my side

**Comment by VulpesStella** [comment]
> welp uhhh..... sorry to be a trouble maker, but i found 2 new problems :|
> 
> 1. both projectiles are invis. they still work and hurt, but invis.
> 2. both slime balls and magma creams are no longer appear on jei. (and maybe the creative menu too).
>    also, just to let you know, im using a lot of different mods, so the issues might only be on my side

No worries. Your feedback is quite helpful.
The absence in creative tabs or jei was caused by a hurry -- the way of registering an item into a tab is different in 1.20 and lower versions, I didn't fix it when backporting.
Currently no idea about that invis glitch, looking into it now.

**Comment by VulpesStella** [comment]
[zipped_mod_file_1.0.2.zip](https://github.com/Nova-Committee/ThrowableSlimeball/files/13114009/zipped_mod_file_1.0.2.zip)

**Comment by mmmthepotatogod** [comment]
yet another issue :|. a small one though
when a projectile hits a honey block, it simply vanishes like my dad (:()
nuh jk, but it does dissappear

**Comment by VulpesStella** [comment]
> yet another issue :|. a small one though when a projectile hits a honey block, it simply vanishes like my dad (:() nuh jk, but it does disappear

```
final BlockState state = level.getBlockState(result.getBlockPos());
if (state.is(ThrowableSlimeball.BLOCK_STICKY)) destroy();
```

It's designed. When a block is in throwable_slimeball:sticky block tag, it will destroy the projectile.

**Comment by mmmthepotatogod** [comment]
ohhhhh thats actually a feature huh? okie dokie.
that being said, THE MOD IS SO FREAKING FUN TO MESS WITH XD
keep the good work!
